LEVELS = [
    {
        'name': '第一关：基础传送',
        'grid_width': 20,
        'grid_height': 15,
        'initial_buildings': [
            {'type': 'producer_red', 'grid_x': 2, 'grid_y': 7},
            {'type': 'conveyor_right', 'grid_x': 3, 'grid_y': 7},
            {'type': 'conveyor_right', 'grid_x': 4, 'grid_y': 7},
            {'type': 'conveyor_right', 'grid_x': 5, 'grid_y': 7},
            {'type': 'conveyor_right', 'grid_x': 6, 'grid_y': 7},
            {'type': 'conveyor_right', 'grid_x': 7, 'grid_y': 7},
            {'type': 'consumer_red', 'grid_x': 8, 'grid_y': 7},
        ],
        'producer_config': {
            'producer_red_0': {'interval': 120, 'resource_type': 'red'},
        },
        'consumer_goals': {
            'red': 10,
        },
        'available_buildings': [
            'conveyor_right', 'conveyor_left', 'conveyor_up', 'conveyor_down',
            'producer_red', 'consumer_red',
        ],
    },
    {
        'name': '第二关：多色资源',
        'grid_width': 20,
        'grid_height': 15,
        'initial_buildings': [
            {'type': 'producer_red', 'grid_x': 2, 'grid_y': 4},
            {'type': 'producer_blue', 'grid_x': 2, 'grid_y': 10},
            {'type': 'conveyor_right', 'grid_x': 3, 'grid_y': 4},
            {'type': 'conveyor_right', 'grid_x': 4, 'grid_y': 4},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 4},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 5},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 6},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 7},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 8},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 9},
            {'type': 'conveyor_right', 'grid_x': 3, 'grid_y': 10},
            {'type': 'conveyor_right', 'grid_x': 4, 'grid_y': 10},
            {'type': 'conveyor_up', 'grid_x': 5, 'grid_y': 10},
            {'type': 'conveyor_up', 'grid_x': 5, 'grid_y': 11},
            {'type': 'conveyor_up', 'grid_x': 5, 'grid_y': 12},
            {'type': 'conveyor_up', 'grid_x': 5, 'grid_y': 13},
        ],
        'producer_config': {
            'producer_red_0': {'interval': 150, 'resource_type': 'red'},
            'producer_blue_0': {'interval': 150, 'resource_type': 'blue'},
        },
        'consumer_goals': {
            'red': 8,
            'blue': 8,
        },
        'available_buildings': [
            'conveyor_right', 'conveyor_left', 'conveyor_up', 'conveyor_down',
            'producer_red', 'producer_blue',
            'consumer_red', 'consumer_blue',
        ],
    },
    {
        'name': '第三关：过滤器使用',
        'grid_width': 20,
        'grid_height': 15,
        'initial_buildings': [
            {'type': 'producer_red', 'grid_x': 2, 'grid_y': 3},
            {'type': 'producer_blue', 'grid_x': 2, 'grid_y': 11},
            {'type': 'conveyor_right', 'grid_x': 3, 'grid_y': 3},
            {'type': 'conveyor_right', 'grid_x': 4, 'grid_y': 3},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 3},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 4},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 5},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 6},
            {'type': 'conveyor_down', 'grid_x': 5, 'grid_y': 7},
            {'type': 'conveyor_right', 'grid_x': 3, 'grid_y': 11},
            {'type': 'conveyor_right', 'grid_x': 4, 'grid_y': 11},
            {'type': 'conveyor_up', 'grid_x': 5, 'grid_y': 11},
            {'type': 'conveyor_up', 'grid_x': 5, 'grid_y': 10},
            {'type': 'conveyor_up', 'grid_x': 5, 'grid_y': 9},
            {'type': 'conveyor_up', 'grid_x': 5, 'grid_y': 8},
            {'type': 'conveyor_right', 'grid_x': 6, 'grid_y': 7},
            {'type': 'conveyor_right', 'grid_x': 7, 'grid_y': 7},
        ],
        'producer_config': {
            'producer_red_0': {'interval': 100, 'resource_type': 'red'},
            'producer_blue_0': {'interval': 100, 'resource_type': 'blue'},
        },
        'consumer_goals': {
            'red': 12,
            'blue': 12,
        },
        'available_buildings': [
            'conveyor_right', 'conveyor_left', 'conveyor_up', 'conveyor_down',
            'producer_red', 'producer_blue',
            'consumer_red', 'consumer_blue',
            'filter_red', 'filter_blue',
        ],
    },
    {
        'name': '第四关：复杂网络',
        'grid_width': 22,
        'grid_height': 18,
        'initial_buildings': [
            {'type': 'producer_red', 'grid_x': 2, 'grid_y': 5},
            {'type': 'producer_blue', 'grid_x': 2, 'grid_y': 12},
            {'type': 'producer_green', 'grid_x': 2, 'grid_y': 9},
        ],
        'producer_config': {
            'producer_red_0': {'interval': 90, 'resource_type': 'red'},
            'producer_blue_0': {'interval': 90, 'resource_type': 'blue'},
            'producer_green_0': {'interval': 90, 'resource_type': 'green'},
        },
        'consumer_goals': {
            'red': 15,
            'blue': 15,
            'green': 15,
        },
        'available_buildings': [
            'conveyor_right', 'conveyor_left', 'conveyor_up', 'conveyor_down',
            'producer_red', 'producer_blue', 'producer_green',
            'consumer_red', 'consumer_blue', 'consumer_green',
            'filter_red', 'filter_blue', 'filter_green',
        ],
    },
]
